///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModel {
/*
{
  "message": "Kullanıcı doğrulandı",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11aGFtbWVkQGdtYWlsLmNvbSIsImlhdCI6MTY0ODU3NTI3OH0.wYRL6VB1fdlWvldx1h8M9bQt8eTMIbFsys606g4u4lg",
  "status": true
} 
*/

  String? message;
  String? token;
  bool? status;

  LoginModel({
    this.message,
    this.token,
    this.status,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    token = json['token']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['token'] = token;
    data['status'] = status;
    return data;
  }
}
