///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class IsCompleteModel {
/*
{
  "message": "Notun durumu bşarıyla değiştirildi",
  "status": true
} 
*/

  String? message;
  bool? status;

  IsCompleteModel({
    this.message,
    this.status,
  });
  IsCompleteModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
